# Generated by Django 3.2.25 on 2025-09-15 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_user', '__first__'),
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('file', models.FileField(null=True, upload_to='Journal_papers')),
                ('file_image', models.ImageField(blank=True, null=True, upload_to='Journal_Papers_image')),
                ('new_category', models.CharField(blank=True, help_text='Only add new Category if you do not see your wise category in Category Choice list.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Under Review', 'Peer Review'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Reviewer Published', 'Reviewer Published'), ('Admin Published', 'Admin Published')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_user.category')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewer.reviewer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'db_table': 'tbl_article',
                'permissions': (('view_publish_articles_to_sites', 'Can view published articles to sites'), ('publish_articles_to_sites', 'Can Published articles to pites'), ('article_publish_to_admin_by_reviewer', 'Can publish  article to admin'), ('check_article', 'Can check  user articles'), ('each_article_view', 'Can  view each articles '), ('view_unpublish_articles', 'Can view unPublished articles')),
            },
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], default='Male', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normal_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'normal_user',
                'verbose_name_plural': 'normal_user',
                'db_table': 'tbl_normal_user',
                'permissions': (('normal_user_view_by_reviewer', 'Can View Normal User of Reviewer Part'),),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.normaluser')),
            ],
        ),
    ]
