# Generated by Django 3.2.25 on 2025-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='google_scholar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Separate interests with commas'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='researchgate',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
