# Generated by Django 3.2.25 on 2025-10-27 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20251027_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='normal_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normaluser', to=settings.AUTH_USER_MODEL),
        ),
    ]
